local _, L = ...;
if GetLocale() == "deDE" then
    L["Altar der See"] = "Altar of the Sea"
    L["30Haste"] = "+30% Tempo"
    L["Periodic Frost Damage"] = "Periodischer Frostschaden"
    L["Verfluchte Opfergabe"] = "Cursed Offering"
    L["30mastery"]  = "+30% Meisterschaft"
    L["50health"] = "-50% Leben"
    L["Todeszauberschutz"] = "Death Ward"
    L["30shadowDone"] = "+30% Schattenschaden und Proccs"
    L["50holyTaken"] = "+50% erlittener Heiligschaden"
    L["Tiefenwaldtotem"] = "Deepwoods Totem"
    L["30natureDone"] = "30% Naturschaden und Proccs"
    L["50arcanTaken"] = "+50% erlittener Arkanschaden"
    L["Mondberührte Ruinen"] = "Moon-Touched Ruins"
    L["30crit"] = "+30% kritische Trefferwertung"
    L["50magicTaken"] = "+50% erlittener Magieschaden"
    L["Überwuchertes Relikt"] = "Overgrown Relic"
    L["30holyDone"] = "+30% Heiligschaden"
    L["50shadowTaken"] = "+50% erlittener Schattenschaden"
    L["Säule der Hüter"] = "Pillar of the Watchers"
    L["30healDoneAndTaken"] = "+30% erhaltene und zugefügte Heilung"
    L["nodef"] = "Kann nicht Parrieren, Ausweichen oder Blocken";
    L["Urzeitlicher Schrein"] = "Primal Shrine"
    L["30physicalDone"] = "+30% physischer Schaden"
    L["50armor"] = "-50% Rüstung"
    L["Runenverzierter Stein"] = "Rune-Etched Stone"
    L["30arcanDone"] = "+30% Arkanschaden und -proccs"
    L["50natureTaken"] = "+50% erlittener Naturschaden"
    L["Der Schlängelnde Schrein"] = "Slithering Shrine"
    L["30move"] = "+30% Bewegungsgeschwindigkeit"
    L["buffAndPurgeDoes80pDmg"] = "80% Max HP beim erhalten udn verlieren des Buffs"
    L["Geisterbecken"] = "Spirit Font"
    L["Retaliation Damage Procs"] = ""
    L["none"] = "keine"
    L["Rast des Wanderers"] = "Wanderer's Respite"
    L["30versa"] = "+30% Vielseitigkeit"
    L["60healTaken"] = "-60% erhaltene Heilung"
    L["Feuerherzgötze"] = "Fireheart Idol"
    L["30firedone"] = "+30% verursachter Feuerschaden"
    L["50frosttaken"] = "+50% erlittener Frostschaden"
	
    L["azeriteString"] = "(%d+) Azerit.+von (.+)|r gesammelt"
	L["azeriteCollected"] = "Azerit.+von.+gesammelt"
	
	L["Disable Azerite Spam"] = "Azeritspam deaktivieren"
    L["Hide all Azerite related collection messages from the chat."] = "Versteckt alle azeritbezogenen Meldungen aus dem Chat."
end